-- AlterTable
ALTER TABLE "User" ALTER COLUMN "email" DROP DEFAULT,
ALTER COLUMN "firstName" DROP DEFAULT,
ALTER COLUMN "lastName" DROP DEFAULT,
ALTER COLUMN "password" DROP DEFAULT,
ALTER COLUMN "university_tie" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;
